project_name: espcn

model:
  network: espcn

dataset:
  name: bsds500
  img_size: 300
  channel: 1
  scale_factor: 3

train:
  learning_rate: 0.001
  epochs: 25
  batch_size: 32

inference:
  num_samples: 16

device: cuda