project_name: ddim

model:
  num_res_blocks: 2
  base_channel: 64
  time_embed_channel: null
  ch_mult: [1, 2, 4]
  num_time_step: 1000
  num_sample_step: 100
  betas: [0.0001, 0.02]
  eta: 0.0
  network: ddim

dataset:
  name: mnist
  channel: 1
  img_size: 28

train:
  learning_rate: 0.0002
  epochs: 5
  batch_size: 128

inference:
  num_samples: 16

device: cuda