project_name: vdsr

model:
  num_layers: 16
  network: vdsr

dataset:
  name: bsds500
  img_size: 300
  channel: 1
  scale_factor: 2

train:
  learning_rate: 0.001
  epochs: 25
  batch_size: 8
  clip_grad: 0.4

inference:
  num_samples: 16

device: cuda