project_name: cgan

model:
  linear:
    latent_dim_linear: 100
    G_hidden_dims: [128, 256, 512]
    D_hidden_dims: [512, 256, 128]
  conv:
    G_mid_channels: [256, 128, 64]
    D_mid_channels: [64, 128, 256]
    latent_dim_conv: 100
  proj_dim: 10
  network: cgan_conv

dataset:
  name: mnist
  channel: 1
  img_size: 28
  num_classes: 10

train:
  generator_lr: 0.0003
  discriminator_lr: 0.0003
  epochs: 50
  batch_size: 64
  d_step: 1
  g_step: 1

inference:
  num_samples: 64

device: cuda