project_name: googlenet

model:
  dropout: 0.5
  network: googlenet

dataset:
  name: cifar100
  img_size: 224
  channel: 3
  num_classes: 100

train:
  learning_rate: 0.001
  epochs: 40
  batch_size: 64

inference:
  num_samples: 32

device: cuda