project_name: densenet

model:
  growth_rate: 12
  dropout: 0.5
  network: densenet121

dataset:
  name: cifar100
  img_size: 224
  channel: 3
  num_classes: 100

train:
  learning_rate: 0.001
  epochs: 40
  batch_size: 32

inference:
  num_samples: 32

device: cuda