project_name: resnet

model:
  network: resnet152

dataset:
  name: cifar100
  img_size: 224
  channel: 3
  num_classes: 100

train:
  learning_rate: 0.001
  epochs: 30
  batch_size: 64

inference:
  num_samples: 32

device: cuda