project_name: ae

model:
  linear:
    latent_dim_linear: 10
    hidden_dims: [256, 128, 64]
  conv:
    mid_channels: [16, 32, 64]
    latent_dim_conv: 10
    kernel_size: 3
  img_size: 28
  channel: 1
  network: ae_conv

train:
  learning_rate: 0.001
  epochs: 25
  batch_size: 64

inference:
  num_samples: 64

device: cuda