project_name: wgan

model:
  in_channel: 1
  G_mid_channels: [256, 128, 64]
  D_mid_channels: [64, 128, 256]
  latent_dim: 100
  out_channel: 1
  network: wgan

train:
  generator_lr: 0.00005
  discriminator_lr: 0.00005
  clip_value: 0.01
  epochs: 50
  batch_size: 64
  d_step: 5
  g_step: 1

inference:
  num_samples: 64

device: cuda