project_name: dcgan

model:
  in_channel: 1
  G_mid_channels: [256, 128, 64]
  D_mid_channels: [64, 128, 256]
  latent_dim: 100
  out_channel: 1
  network: dcgan

train:
  generator_lr: 0.0002
  discriminator_lr: 0.0002
  epochs: 50
  batch_size: 64
  d_step: 1
  g_step: 5

inference:
  num_samples: 64

device: cuda