project_name: cvae

model:
  linear:
    latent_dim_linear: 10
    hidden_dims: [512, 128, 32]
  conv:
    mid_channels: [16, 32, 64]
    latent_dim_conv: 10
    kernel_size: 3
  network: cvae_conv

dataset:
  name: mnist
  img_size: 28
  channel: 1
  num_classes: 10

train:
  learning_rate: 0.001
  epochs: 25
  batch_size: 64

inference:
  num_samples: 64

device: cuda