project_name: transunet

model:
  out_channel: 128
  patch_size: 16
  num_layers: 6
  num_heads: 8
  mlp_dim: 1024
  network: transunet

dataset:
  name: carvana
  img_size: 512
  channel: 3
  num_classes: 1

train:
  learning_rate: 0.001
  epochs: 30
  batch_size: 2

inference:
  num_samples: 32
  mask_threshold: 0.75

device: cuda