project_name: inception_v3

model:
  num_classes: 100
  dropout: 0.5
  network: inception_v3
  img_size: 299

train:
  learning_rate: 0.001
  epochs: 40
  batch_size: 32

inference:
  num_samples: 32

device: cuda