project_name: vqvae

model:
  num_embeddings: 512
  embed_dim: 256
  num_res_blocks: 2
  beta: 0.25
  feature_size: 7
  network: vqvae

prior:
  mid_channel: 128
  num_res_blocks_prior: 15
  network: pixelcnn

dataset:
  name: mnist
  img_size: 28
  channel: 1

train:
  model:
    learning_rate: 0.0002
    epochs: 25
    batch_size: 64
  prior:
    learning_rate: 0.0003
    epochs: 25
    batch_size: 128

inference:
  num_samples: 64

device: cuda