project_name: wgan-gp

model:
  G_mid_channels: [256, 128, 64]
  D_mid_channels: [64, 128, 256]
  latent_dim: 100
  network: wgan-gp

dataset:
  name: mnist
  channel: 1
  img_size: 28

train:
  generator_lr: 0.0001
  discriminator_lr: 0.0001
  grad_penalty_weight: 10
  epochs: 10
  batch_size: 64
  d_step: 5
  g_step: 1

inference:
  num_samples: 64

device: cuda