project_name: wgan-gp

model:
  in_channel: 1
  G_mid_channels: [256, 128, 64]
  D_mid_channels: [64, 128, 256]
  latent_dim: 100
  out_channel: 1
  network: wgan-gp

train:
  generator_lr: 0.0001
  discriminator_lr: 0.0001
  grad_penalty_weight: 10
  epochs: 25
  batch_size: 64
  d_step: 5
  g_step: 1

inference:
  num_samples: 64

device: cuda