project_name: gan

model:
  latent_dim: 100
  G_hidden_dims: [128, 256, 512]
  D_hidden_dims: [512, 256, 128]
  network: gan

dataset:
  name: mnist
  channel: 1
  img_size: 28

train:
  generator_lr: 0.0003
  discriminator_lr: 0.0003
  epochs: 50
  batch_size: 64
  d_step: 1
  g_step: 1

inference:
  num_samples: 64

device: cuda