project_name: gan

model:
  input_dim: 1024
  latent_dim: 100
  G_hidden_dims: [128, 256, 512]
  D_hidden_dims: [512, 256, 128]
  output_dim: 1024
  network: gan

train:
  generator_lr: 0.0003
  discriminator_lr: 0.0003
  epochs: 50
  batch_size: 64
  d_step: 1
  g_step: 1

inference:
  num_samples: 64

device: cuda