project_name: vit

model:
  patch_size: 4
  num_encoders: 6
  num_heads: 8
  mlp_dim: 1024
  dropout: 0.1
  network: vit

dataset:
  name: cifar10
  img_size: 32
  channel: 3
  num_classes: 10

train:
  learning_rate: 0.0001
  epochs: 50
  batch_size: 64

inference:
  num_samples: 32

device: cuda