project_name: rnn

model:
  embed_dim: 512
  hidden_dim: 512
  num_layers: 1
  dropout: 0.2
  bidirectional: False
  network: lstm

dataset:
  name: imdb
  num_classes: 2

train:
  learning_rate: 0.001
  epochs: 40
  batch_size: 256

inference:
  num_samples: 8

device: cuda