project_name: seq2seq

model:
  embed_dim: 256
  hidden_dim: 512
  num_layers: 2
  encode_dropout: 0.2
  decode_dropout: 0.2
  bidirectional: False
  network: gru_attn

train:
  learning_rate: 0.001
  epochs: 40
  batch_size: 256

inference:
  num_samples: 64

device: cuda