project_name: alexnet

model:
  num_classes: 100
  dropout: 0.5
  network: alexnet
  img_size: 224

train:
  learning_rate: 0.0005
  epochs: 40
  batch_size: 128

inference:
  num_samples: 64

device: cuda