project_name: drrn

model:
  mid_channel: 128
  num_layers: 1
  recurse_depth: 25
  network: drrn

dataset:
  name: bsds500
  img_size: 300
  channel: 1
  scale_factor: 2

train:
  learning_rate: 0.001
  epochs: 25
  batch_size: 4

inference:
  num_samples: 16

device: cuda