project_name: vgg

model:
  network: vgg16
  dropout: 0.5

dataset:
  name: cifar100
  img_size: 224
  channel: 3
  num_classes: 100

train:
  learning_rate: 0.001
  epochs: 15
  batch_size: 64

inference:
  num_samples: 64

device: cuda