project_name: alexnet

model:
  dropout: 0.5
  network: alexnet

dataset:
  name: cifar100
  img_size: 224
  channel: 3
  num_classes: 100

train:
  learning_rate: 0.0001
  epochs: 100
  batch_size: 128

inference:
  num_samples: 64

device: cuda