project_name: srgan

model:
  base_channel: 64
  num_blocks_g: 16
  num_blocks_d: 7
  network: srgan

dataset:
  name: bsds500
  img_size: 256
  channel: 3
  scale_factor: 2

train:
  generator_lr: 0.0001
  discriminator_lr: 0.0001
  epochs: 50
  pretrain_epochs: 10
  batch_size: 4
  d_step: 1
  g_step: 1

inference:
  num_samples: 16

device: cuda