project_name: began

model:
  base_channel: 64
  num_layers: 3
  latent_dim: 64
  lambda_k: 0.001
  gamma: 0.5
  k: 0.0
  network: began

dataset:
  name: mnist
  channel: 1
  img_size: 28

train:
  generator_lr: 0.0001
  discriminator_lr: 0.0001
  epochs: 20
  batch_size: 64
  d_step: 1
  g_step: 1

inference:
  num_samples: 64

device: cuda