project_name: drcn

model:
  inference_depth: 4
  alpha: 1.0
  alpha_decay_epoch: 25
  beta: 0.0001
  network: drcn

dataset:
  name: bsds500
  img_size: 300
  channel: 1
  scale_factor: 2

train:
  learning_rate: 0.001
  epochs: 50
  batch_size: 2

inference:
  num_samples: 16

device: cuda