project_name: sngan

model:
  in_channel: 1
  G_mid_channels: [512, 256, 128, 64]
  D_mid_channels: [64, 128, 256, 512]
  latent_dim: 128
  out_channel: 1
  feature_size: 4
  network: sngan

train:
  generator_lr: 0.0002
  discriminator_lr: 0.0002
  epochs: 30
  batch_size: 64
  d_step: 1
  g_step: 1

inference:
  num_samples: 64

device: cuda