project_name: sngan

model:
  G_mid_channels: [512, 256, 128, 64]
  D_mid_channels: [64, 128, 256, 512]
  latent_dim: 128
  network: sngan

dataset:
  name: mnist
  channel: 1
  img_size: 28

train:
  generator_lr: 0.0002
  discriminator_lr: 0.0002
  epochs: 10
  batch_size: 64
  d_step: 1
  g_step: 1

inference:
  num_samples: 64

device: cuda